.github/workflows/longtest.yml
Skip a workaround used by the 'julia-runtest' action for the case when the Julia 'General Registry' is not perfectly up to date - requires a file from that action, so rather than copying the file just skip as it doesn't seem to be too important. Also remove `force_latest_compatible_version` argument to `Pkg.test()` which caused an error.
=> Fix long tests in CI

src/finite_differences.jl, src/quadrature.jl, test/calculus_tests.jl
Found a small bug in the 'finite difference' integration weights. For grids with an odd number of points, the weights for points 5 and upward were the wrong way around. Found by adding a finite difference variant to the calculus unit test (which I did while looking to copy the pattern for a test of an interpolation function).
The difference:
```
previously weights were: h/3, 4h/3, 2h/3, 4h/3, 4h/3, 2h/3, 4h/3, ...
weights should be      : h/3, 4h/3, 2h/3, 4h/3, 2h/3, 4h/3, 2h/3, ...
=> Fix uniform-grid integration weights and FD derivatives on more than 1 element

Project.toml, README.md, util/print-macros.jl
Adds a script that prints all the loop macros created in the `looping` module along with macro-expansions of an example call.
We talked about writing to a file. Could do that easily if people prefer, but having got this far just printing to stdout seemed like a reasonable thing to do: not being saved to a file it's clear that the output is just output and can't be edited to change the code, etc.
Also includes a commit bumping the required Julia version to 1.7.0. Also adds the version requirement to the `Project.toml`, which I'd hoped would result in nicer error messages if someone tries to use a too-old version of Julia, but unfortunately this seems not to be the case: https://discourse.julialang.org/t/strange-error-for-unsupported-julia-version/74489
=> Macro expansion examples

.github/workflows/examples.yml, README.md, util/print-macros.jl
When used to index the example array, the indices printed by `util/print-macros.jl` were in the reverse of the correct order.
Also fix typo in `README.md`.
=> Fix loop macro documentation

debug_test/README.md, src/communication.jl
Refactor `debug_check_shared_array()` out as a separate function, and use it in `debug_check_shared_memory()`.
`debug_check_shared_memory()` is only available when a high enough debugging level is set (so `@debug_shared_array` is active), and is not used normally but can be added to help pin down where exactly a shared-memory error occurred.
=> Add debugging function debug_check_shared_memory()

src/continuity.jl, src/energy_equation.jl, src/force_balance.jl, src/time_advance.jl
When @mrhardman and I were talking earlier, we were puzzled by this construction
https://github.com/mabarnes/moment_kinetics/blob/74e16e935304ade85fcd46c2071c0185864ab5d4/src/time_advance.jl#L665-L669
The motivation for it was that the moment updates in `continuity_equation!()`, etc., need to take z-derivatives, so they can only parallelize over species. This was being done by using `@s_z_loop_s`, and then `if 1 in loop_ranges[].s_z_loop_z`, in order to avoid changing the loop type.
It seems clearer to instead completely separate the part of euler_time_advance!() that updates the distribution function (by moving the boundary condition application from the bottom of euler_time_advance!() to the end of the distribution function update), and then use `begin_s_region(no_synchronize=true)` …
=> Use begin_s_region() for moment updates

debug_test/README.md, performance-tests/plot_performance.jl
Update debugging docs: remove reference to `@debug_loop_type_region` that was removed in #45; mention that the current 'loop type region' can be identified by looking at `loop_ranges[].parallel_dims`.
Fix bug in `plot_performance.jl` that caused an error when results for a machine did not contain entries for every nproc present in the database.
=> Addition to debugging docs; fix bug in plot_performance.jl

README.md, docs/make.jl
Makes it easier to find from the github.com repo.
The link also appears on the 'Getting started' page of the docs, because that page is a copy of the top-level README.md. Possibly mildly confusing, but I think having the info in both places is useful, and having a link in a slightly odd place is better than duplicating the documentation. It would be nicer if Markdown had a way to include one file in another file, but it doesn't - downside of a 'minimal' documentation syntax.
=> Add link to the documentation webpage in README.md

src/continuity.jl, src/initial_conditions.jl, src/ionization.jl, src/moment_kinetics.jl, src/time_advance.jl, src/velocity_moments.jl
This branch has all of the changes needed to reproduce the results from the standard drift kinetic equation for the case with a wall BC and including ionization collisions, but with the pdf normalised by density so that a continuity equation has to be solved to evolve the density.
=> version that supports evolve_density = true with 'wall' BC and ionization collisions

src/force_balance.jl, src/initial_conditions.jl, src/time_advance.jl, src/vpa_advection.jl
added option to evolve upar as well as density with ionization collisions and wall BC.  Use of the peculiar velocity as a phase space coordinate, as is done for upar evolution, is not recommended for use with the wall BC, given the fact that the wall BC works with dz/dt as a coordinate rather than the peculiar velocity.
=> Upar evolution wall bc

src/moment_kinetics.jl
If just one process throws an exception, we need to catch it and call `MPI.Abort()` to stop all processes.
Also uses a `try...finally...end` construct to try to call `cleanup_moment_kinetics!()` when an error occurs, to close output files properly, etc. This can probably fail if `MPI.Abort()` is called as I guess `MPI.Abort()` kills the other processes without waiting for exception handling. Unfortunately I don't know of a decent solution for error/exception handling with MPI...
Fixes #65.
=> Stop all MPI processes when an error occurs

src/file_io.jl
Pass array references when writing to NetCDF file. Apparently broadcasting the write operation is significantly slow. Instead pass the Array directly (as used to be done), but with a special work-around for DebugMPISharedArray which avoids (forbidden) implicit conversion to Array.
=> Fix slowdown of NetCDF file writing

restart_moment_kinetics.jl, src/command_line_options.jl, src/communication.jl, src/file_io.jl, src/moment_kinetics.jl, src/time_advance.jl, test/nonlinear_sound_wave_tests.jl
Add a function `restart_moment_kinetics()` that allows restarting a run from any time point in an existing output file.
Save the normalized pdf rather than an unnormalized one to output files - makes restarting simpler as the normalized pdf is the evolved variable.
Call MPI.Abort() if an error occurs on any process, printing the error message first. This helps to avoid a run hanging if an error occurs on only one (or a few) processes.
=> Enable restarting of runs

src/moment_constraints.jl, src/moment_kinetics.jl, src/time_advance.jl, src/velocity_moments.jl
Updates to moment constraints:
* Use the full pdf everywhere, rather than using a symmetrized pdf in some terms. This makes the expressions a bit more complicated but avoids issues near sheath boundaries: the previous form would add some correction terms proportional to `f_sym = (f(vpa)+f(-vpa))/2`, but these corrections are non-zero in the part of velocity space where the f_ion is forced to be zero at the sheath entrance, and are also not ideal for f_neutral at the wall as f_neutral is not symmetric and has a sharp feature where the outgoing Knudsen distribution joins on to the incoming distribution.
* Use f at the current timestep to correct the moments, rather than f at the previous timestep. Requires computing several moments of the 'initial guess' for f, so a bit more expensive, but …
=> Make moment constraints interact better with boundary conditions

docs/src/numerical_dissipation.md, src/calculus.jl, src/chebyshev.jl, src/coordinates.jl, src/finite_differences.jl, src/moment_kinetics.jl, src/moment_kinetics_input.jl, src/moment_kinetics_structs.jl, src/numerical_dissipation.jl, src/time_advance.jl, test/calculus_tests.jl
Introduces a collection of functions to add numerical dissipation, all disabled by default. Currently, these seem to be useful to avoid a numerical (?) instability in the initial stages of wall-bc runs.
The dissipation is switched on and controlled by input parameters. These parameters are passed in a section `[numerical_dissipation]` in the TOML files.
Adds a second derivative function to be used for numerical dissipation. Finite difference version is standard second order centred difference. The Chebyshev pseudospectral version is a tentative attempt at an implementation; the current implementation does the following:
* Take the first derivative, storing the values in each separate element
* Get the continuous first derivative at element boundaries by averaging the values from both …
=> Second derivative and numerical dissipation

.github/workflows/examples.yml, src/moment_kinetics.jl, src/numerical_dissipation.jl, src/time_advance.jl
Introduces a function `force_minimum_pdf_value!()` that can be used to set any values less than the minimum to the minimum. Forcing `f >= 0.0` can sometimes help numerical stability when running in moment-kinetic mode, as negative values sometimes seem to 'confuse' the algorithm applying the constraints. However sometimes applying this forcing reduces the accuracy of the simulation - for example in the Harrison-Thompson test, forcing a minimum of 0 pushes the numerical solution far from the analytical one with errors ~100% rather than errors <3%.
By default no minimum value is applied. The value to use can be set in input options (0.0 is probably the most useful choice...) like
```
[numerical_dissipation]
force_minimum_pdf_value = 0.0
```
The forcing applied before applying boundary …
=> Allow forcing a minimum value for the pdf

src/continuity.jl, src/energy_equation.jl, src/force_balance.jl, src/numerical_dissipation.jl, src/time_advance.jl, test/nonlinear_sound_wave_tests.jl
Use upwinding at element boundaries in the moment equations: helps avoid numerical instability in moment-kinetic runs with wall boundary conditions.
Also add an option for adding diffusion (for numerical dissipation) in the moment equations, disabled by default.
Move the conversion from 'particle flux' to 'parallel flow' inside the `force_balance!()` function. This just makes `euler_time_advance!()` look a bit neater.
I wonder if the z-derivatives of moments that appear in the drift kinetic equation for moment-kinetic cases need to use upwinding in a way somehow consistent with the moment equations. I'm still testing whether this makes any significant difference...
=> Add upwinding in moment equations

examples/wall-bc/wall-bc_cheb_split1.toml, examples/wall-bc/wall-bc_cheb_split2.toml, examples/wall-bc/wall-bc_cheb_split3.toml, src/energy_equation.jl, src/ionization.jl, src/source_terms.jl, src/vpa_advection.jl
* `ionization_collisions!()` uses `fvec.dens` and `fvec.upar` instead of `moments.dens` and `moments.upar` as the `moments` versions are only updated at the end of the full timestep, not at each RK stage.
* fix index error in interpolation for evolving_upar case in `ionization_collisions!()`
* add missing contributions like (u[s]-u[s'])^2 to ionization terms in energy equation, and in places where energy equation contributes to `vpa_advection!()` and `source_terms!()`.
With these fixes, I have a 'full moment-kinetic' case (evolving density, upar and ppar) with wall boundary conditions that runs and agrees pretty well with the 'full-f' and 'evolving upar' cases!
=> Ionization fixes

src/file_io.jl, src/file_io_hdf5.jl, src/file_io_netcdf.jl, src/moment_kinetics.jl
Previously, when a simulation crashed it would corrupt the output files. Prevent this by closing the output files once writing of one step is finished, and re-open them each output step.
It would be easy to make this feature something we could switch on/off with an input option, but unless opening the HDF5/NetCDF files becomes a significant performance bottleneck I think this new version is just better, so no need to add another input parameter.
If we did want to implement, all that should need to be done is to, if the switch is set, return the I/O info structs (like it was before this PR) from `setup_file_io()` instead of filenames. Everything else should 'just work'.
=> Close output files when not reading/writing

src/moment_kinetics.jl, src/moment_kinetics_input.jl
When `mk_input()` is called from `setup_moment_kinetics()`, it needs to set up distributed memory MPI, but otherwise (e.g. in post-processing) it is just used to recreate the inputs used for a run, so does not need to set up distributed MPI.
=> Skip distributed MPI setup in mk_input() except when running simulation

machines/archer/jobscript-precompile.template
The 16GB limit was leading to out-of-memory errors when precompiling with julia-1.8.5 (although not with julia-1.9.2), so increase limit to 64GB.
=> Increase memory limit for precompile job on archer

src/load_data.jl
The name of the variable to load should be "thermal_speed_neutral" not "thermal_speed" (which is the ion thermal speed). Would only have affected moment-kinetic runs using `evolve_ppar`, so should have been a very minor bug.
=> Fix variable name for re-loading neutral thermal speed

docs/src/input_options.md, src/analysis.jl, src/communication.jl, src/input_structs.jl, src/makie_post_processing.jl, src/moment_kinetics_input.jl, src/time_advance.jl
When running a simulation to steady state, it is useful to be able to check how close it is to converging to steady state (#106).
Define an 'absolute residual' for some variable $a$
```math
r_{\mathrm{abs}}(t,x) = \frac{|a(t,x) - a(t-\delta t,x)|}{\delta t}
```
and a 'relative residual'
```math
r_{\mathrm{rel}}(t,x) = \left(\frac{a(t,x) - a(t-\delta t,x)}{\delta t (\left|a(t,x)\right| + \epsilon)}\right)^2
```
This PR adds functionality for calculating and checking these residuals:
* In post-processing, calculate the maximum and RMS (over the spatial dimensions $x$) of both absolute and relative residuals for any field and moment variables, if `steady_state_residual = true` is set in the post-processing input file. The 4 residuals are written to a text file in the run directory, and …
=> Calculate and check steady state residuals

src/makie_post_processing.jl
* Add missing `!is_1D` to avoid making empty plot vs r from 1D run
* Fix for caching when animating output from long runs - was an error if the total number of time points was not a multiple of the number of time points per chunk
* Fix an error where `postproc_load_data()` would not actually load any data for a run with multiple restarts if the subset of time points being loaded did not include a point in the first restart's output file.
=> Small fixes for makie_post_processing

README.md, src/input_structs.jl, src/moment_kinetics_input.jl, src/time_advance.jl
When running in the REPL (especially with MPI) interrupting a run using Ctrl-C can mess things up, and require you to restart Julia. There is also a chance that you might interrupt while writing the output files and corrupt them. To
avoid these problems, this PR adds a feature to stop the run cleanly, by creating an empty file called `stop` in the run directory. For example, if the name of your run is 'my\_example'
```shell
$ touch runs/my_example/stop
```
`moment_kinetics` checks for this file when it is going to write output, and if it is present writes all output and then returns cleanly. The 'stop file' is deleted when a run is (re-)started, if present, so you do not have to manually delete it before (re-)starting the run again.
=> `stop` file to stop a run cleanly

src/file_io.jl, src/moment_kinetics.jl, src/moment_kinetics_input.jl
Make the `restart_filename` argument to `restart_moment_kinetics()` optional. By default, restart from the most recent output file in the run directory (the one with no `_<i>` suffix in the name).
This required re-ordering the arguments of `restart_moment_kinetics` so that `input_filename` is first, and `restart_filename` is second.
=> Restart from most recent output file by default

machines/archer/jobscript-postprocess-plotsjl.template, machines/archer/jobscript-postprocess.template, machines/archer/jobscript-precompile-no-run.template, machines/archer/jobscript-precompile-postprocessing.template, machines/archer/jobscript-precompile.template, machines/marconi/jobscript-postprocess-plotsjl.template, machines/marconi/jobscript-postprocess.template, machines/marconi/jobscript-precompile-no-run.template, machines/marconi/jobscript-precompile-postprocessing.template, precompile-makie-post-processing.jl, precompile-no-run.jl, precompile-submit.sh, precompile.jl, precompile_dependencies.jl, submit-restart.sh, submit-run.sh, util/precompile_makie_plots.jl
* There was a bug in `util/precompile_makie_plots.jl` which meant that precompiling makie_post_processing would fail.
* Add an option in `submit-run.sh` and `submit-restart.sh` to just create submission scripts, not actually submit the jobs. This is useful if you want to edit the submission scripts by hand for some reason.
* Uses `run_makie_post_processing.jl` in the cluster post-processing job. ~~(To change this locally, edit `machines/archer/jobscript-postprocess.template`, etc.)~~ To use the original `post_processing.jl` instead, pass the flag `-o` to the `submit-run.sh` or `submit-restart.sh` scripts.
* Adds the `-O3` flag when compiling the sysimage for post-processing. This should not have any negative consequences (unlike `--check-bounds=no), and might speed things up.
* To avoid …
=> Precompile fixes and improvements

src/time_advance.jl
When writing output, check for NaNs and Allreduce/Bcast the result so that the simulation can stop cleanly. This probably won't cost much, and prevents time/energy being wasted running simulations that are silently producing junk.
=> If a NaN is found, stop the simulation

README.md, machines/README.md, machines/archer/jobscript-restart.template, machines/marconi/jobscript-restart.template, restart_moment_kinetics.jl, src/command_line_options.jl, src/communication.jl, src/moment_kinetics.jl, src/post_processing.jl, submit-restart.sh
Move actual implementation of restart functionality inside setup_moment_kinetics!() - this also fixes a bug where `iblock_index[]` was not initialised when `get_backup_filename()` needed to use it.
This allows the `restart_moment_kinetics()` function to be removed. It is replaced by a couple of arguments to run_moment_kinetics.
The `restart_moment_kinetics.jl` script is removed. Now either pass the `--restart` flag to `run_moment_kinetics()` to restart from the latest file in the run directory, or pass the output file to restart from as the second positional argument.
=> Simplify restart functionality

.github/workflows/test.yml, src/chebyshev.jl, src/coordinates.jl, src/file_io.jl, src/input_structs.jl, src/load_data.jl, src/moment_kinetics_input.jl, src/post_processing.jl, test/calculus_tests.jl, test/interpolation_tests.jl, test/nonlinear_sound_wave_tests.jl, test/wall_bc_tests.jl
This pull request introduces flexibility into the specification of the element boundaries, naturally allowing packing of points near the wall boundaries for the purpose of capturing the square-root shape of the electric potential near the sheath entrance. The code modifications are minor -- in the specification of the grids, weights, and derivative routines there were variables called "scale_factor" and "shift". Using Gauss-Chebyshev-Lobatto points in the spectral element scheme, we can write these scale and shift factors in terms of differences and averages of the element boundary points. All that is required is to specify the desired locations of the element boundaries at the initial time of the simulation. Previously, element boundaries were assumed to be uniformly spaced.
Access the …
=> Unequally spaced element boundaries for grid optimisations

machines/machine_setup.sh, src/load_data.jl
Using just '.' means the contents of '.julia' get put directly in the top level of the repo - really want to create a '.julia' subdirectory within the repo.
=> Better suggestion for putting .julia locally within the repo in `machine_setup.sh`

src/file_io.jl, src/input_structs.jl, src/load_data.jl, src/post_processing.jl, src/post_processing_input.jl, src/time_advance.jl, src/velocity_moments.jl
This PR provides a generalised Chodura condition diagnostic in the main code (see, for example, eqn 104, A. Geraldini Plasma Phys. Control. Fusion 60 (2018) 125002). The output value should be less that 1 for a stable sheath to form at the boundary layer near the wall (outside the simulation domain here). The current version gives the correct result at the initial time for the 1D1V manufactured solution (1/3). The resulting integrals are computed separately at the upper and lower plates and stored as arrays of time and radius. 
Known problems:
-The current file i/o is not consistent with distributed memory MPI. This is because we can only compute the Chodura conditions at the ends of the domain in z, and we should only save the data in the output file that comes from these locations.
-The …
=> A generalised kinetic Chodura condition with radial dependence

src/file_io.jl, src/file_io_hdf5.jl, src/file_io_netcdf.jl, src/moment_kinetics.jl, src/time_advance.jl, src/utils.jl
Save some run-time information to the output files: time for setup (excluding file I/O), and cumulative run time (excluding setup) at each output step.
=> Save the run-time of simulations to the output file

src/load_data.jl
For old files, can safely default to `element_spacing_option = "uniform"`.
=> Allow loading coordinates from files created before `element_spacing_option` was added

docs/src/post_processing_notes.md, src/makie_post_processing.jl, src/moment_kinetics.jl, test/restart_interpolation_tests.jl
Collection of small fixes and enhancements for Makie-based post processing module.
Several enhancements make interactive use of the module in the Julia REPL better.
Also:
* Plot checks of constraints on normalised distribution function for moment-kinetic runs (i.e. numerically calculate first 3 moments)
* Add a plot of f/vpa^2 to the 'wall plots'
* Allow the sound speed and Mach number to be calculated/plotted/animated (currently using `c_s = sqrt((T_e + gamma*T_i)/m_i)`, with `gamma = 3` which is the value for purely 1D1V flow
=> `makie_post_processing` update

.github/workflows/longtest.yml, src/makie_post_processing.jl, test/restart_interpolation_tests.jl
The 'longtest' job only runs when a PR is merged to `master`, so we didn't see the failure before merging #150.
Best guess is the failure was caused by an out-of-memory error on the Ubuntu runner - although I don't understand why that happened for the 'longtest' job which runs in serial but not for the 'parallel tests' job which does run all the 'long tests' in one of its calls!
Anyway, re-jigging to avoid loading a full 2D3V neutral distribution function into memory seems to fix the problem.
=> Fix 'longtest' CI job

debug_test/restart_interpolation_inputs.jl, src/communication.jl
Add a Bool flag that records whether an array has been accessed at all. If it has not been (on any process in a shared-memory block), can skip the rest of the checks. This significantly speeds up the debug checks.
=> Optimise `@debug_shared_array`

run_moment_kinetics.jl
When running from the command line using the `run_moment_kinetics.jl` script, call `using moment_kinetics` first on rank-0, and only after that has completed call it on all other ranks. Hopefully this avoids precompilation clashes (when multiple MPI ranks try to precompile the same package simultaneously) which might corrupt files. It does not solve the clash issue for importing MPI, because `using MPI` is needed to get the MPI commands to synchronize between rank-0 and the other processes, but hopefully minimises the chance of problems.
=> Precompile on rank-0 first in run_moment_kinetics.jl

examples/wall-bc/wall-bc_volumerecycle.toml, examples/wall-bc/wall-bc_volumerecycle_split1.toml, examples/wall-bc/wall-bc_volumerecycle_split2.toml, examples/wall-bc/wall-bc_volumerecycle_split3.toml, src/file_io.jl, src/neutral_vz_advection.jl
The option `controller_type` was renamed to `source_type` after #147 was written, so needs fixing. Also fix a couple of typos that caused bugs in the 'volumerecycle' examples added in #147.
=> Fix examples introduced in #147

makie_post_processing/makie_post_processing/src/makie_post_processing.jl, moment_kinetics/src/load_data.jl
Also add a couple of minor upgrades for `makie_post_processing`: catch errors when making steady state residual plots; skip (all) plots where one axis is a dimension that only has one point.
=> Fix `kwargs` handling in post-processing loading function `get_variable()`

moment_kinetics/src/load_data.jl
Also fix a bad merge that result in `chodura_ingteral_lower` and `chodura_integral_upper` being reloaded twice.
=> Support loading from older output files that did not have some variables

machines/shared/add_dependencies_to_project.jl, machines/shared/makie_post_processing_setup.jl, machines/shared/plots_post_processing_setup.jl
When using separate post-processing packages and setting up `makie_post_processing` and/or `plots_post_processing`, the machine setup scripts should be editing `makie_post_processing/LocalPreferences.toml` and/or `plots_post_processing/LocalPreferences.toml`. Before this PR the top-level `LocalPreferences.toml` was accidentally modified, which led to the HDF5 library not being linked when using separate post-processing packages (falling back to the bundled-with-Julia HDF5, which meant parallel I/O was not available).
=> Fix HDF5 setup when `separate_postproc_projects="y"`

moment_kinetics/src/communication.jl
Seems to fix issue where loading `Symbolics` would cause MPI error messages. When this happened, running MMS simulations could hang at the end of a run, even though the run completed successfully. The problem seems to have been that somehow loading `Symbolics` caused `MPI.Init()` to be called - it is not allowed to call `MPI.Init()` twice, so when it was called when starting `moment_kinetics`, something bad happened.
=> Make sure MPI.Init() is only ever called once

moment_kinetics/src/communication.jl
Fix the use of 'views' with `MPIDebugSharedArray`.
Set `is_read`/`is_written`/`is_initialized`/`accessed`  fields of `MPIDebugSharedArray` when passed to `MPI.Buffer()`. This ensures that we check that the array is synchronized across the shared-memory block after it is updated (by the root process of the shared-memory block) using distributed-MPI communication.
=> Improve shared-memory debugging when also using distributed-MPI

machines/generic-batch-template/compile_dependencies.sh, machines/generic-pc/compile_dependencies.sh, machines/machine_setup.sh, machines/marconi/compile_dependencies.sh
Replace `realpath` with Python in machine setup script. `realpath` is not necessarily portable, while we already require Python to be available for the Julia-downloader script. Using Python's `os` module should be pretty portable.
Fixes #183.
=> Make machine setup scripts work on MacOS

machines/shared/add_dependencies_to_project.jl
`MPIPreferences.use_system_binary()` does not find the MPI library when it was installed with homebrew on macOS, so prompt for the user to give the path to the MPI library instead.
@LucasMontoya4 does this work for you?
@mabarnes did you need to work around this problem when using the `machines/machine_setup.sh` setup script?
Is there a default that we should check (for non-homebrew setups?) that could find the MPI library automatically? I don't have a Mac to test...
=> In machine_setup.sh on macOS, prompt for MPI library path

moment_kinetics/src/chebyshev.jl, moment_kinetics/src/coordinates.jl, moment_kinetics/src/load_data.jl, moment_kinetics/src/moment_kinetics.jl, moment_kinetics/src/moment_kinetics_input.jl, moment_kinetics/test/calculus_tests.jl, moment_kinetics/test/interpolation_tests.jl, moment_kinetics/test/velocity_integral_tests.jl, moment_kinetics/test/wall_bc_tests.jl
When using `flags=FFTW.MEASURE`, FFTW does some run-time tests to choose the fastest version of its algorithm to use. This can lead to different processes using slightly different algorithms - these should only differ by machine-precision-level rounding errors but (surprisingly!) this may be important. This PR updates so that the FFTW plans are generated on the root process, then written out to an 'FFTW wisdom' file which is read by all other processes, ensuring that all processes use exactly the same algorithm.
While working on the kinetic electrons, I came across a very strange bug. A simulation that would run correctly on a small number of processes (e.g. 8, with the z-direction split into 8 blocks using distributed-memory, so each shared-memory block only has one process), but would …
=> Make all processes use identical FFTW plans

moment_kinetics/src/external_sources.jl, moment_kinetics/src/time_advance.jl, plots_post_processing/plots_post_processing/src/plots_post_processing.jl
Options added to the ion source for the purpose of creating simulations to compare to Mantas Abazorius's thesis results, varying both the target density and temperature of the distribution at the origin of the domain.
Modifications to the plotting script to permit quick comparisons of f/v^2.
=> New ion source options

.github/workflows/debug_checks.yml, .github/workflows/examples.yml, .github/workflows/longtest.yml, .github/workflows/parallel_test.yml, .github/workflows/test.yml, moment_kinetics/test/restart_interpolation_tests.jl
This was missed in #194, and made the 'long tests' very slow, so that they timed out.
=> Handle updated timestepping options in restart_interpolation_tests.jl

examples/geometry/1D-mirror.toml, examples/gk-ions/2D-periodic-gk.toml, util/precompile_run.jl
Changes to the precompile_run.jl file to make sure collisions and geometric features are available in the moment_kinetics.so.
Also update some example files with the new timestepping options. Query whether or not the example input files still contain redundant flags.
=> Update precompilation input deck to reflect updated collisions options.

moment_kinetics/src/looping.jl
We may sometimes call `get_local_range()` with a `sub_block_rank` bigger than the `sub_block_size`, in particular for the `anyv` 'serial region'. In this case immediately return `1:0` for the range, as this avoids a potential out-of-bounds array access when accessing `n_points_for_proc`.
Fixes #210.
=> Fix range setup for `anyv` regions

moment_kinetics/src/chebyshev.jl, moment_kinetics/src/coordinates.jl, moment_kinetics/src/fokker_planck_calculus.jl, moment_kinetics/src/gauss_legendre.jl, moment_kinetics/src/interpolation.jl, moment_kinetics/src/lagrange_polynomials.jl
Precalculate some quantities to minimise the amount of work needed to evaluate the Lagrange polynomials, and hopefully to make the loops vectorise better. Speeds up interpolation by about 3x in one case that I profiled.
=> Optimise 1d Gauss-Legendre interpolation

examples/fokker-planck/fokker-planck-relaxation-report-resolutions.toml, moment_kinetics/src/fokker_planck_test.jl, moment_kinetics/test/fokker_planck_tests.jl, test_scripts/2D_FEM_assembly_test.jl, test_scripts/fkpl_direct_integration_test.jl
Improvement to the `test_scripts/` related to the Fokker-Planck collision operator to permit saving of the error data directly to HDF5 to permit later replotting of the data, and easier comparison of results of the tests on different core counts.
Suggesting to PR into the fix-anyv branch as these branches are thematically linked.
=> Improve collision operator scripts to save HDF5 format error data for easier comparisons

moment_kinetics/ext/file_io_netcdf.jl, moment_kinetics/src/file_io.jl, moment_kinetics/src/file_io_hdf5.jl
Allow `coords` argument to `create_dynamic_variable!()` and `write_single_value!()` to be `NamedTuple` as well as `coordinate`. This change makes it simple to add an extra dimension for which there is not a `coordinate` struct, and simplifies the code by replacing the special-purpose arguments for `n_ion_species`, `n_neutral_species` and `diagnostic_var_size`.
=> Simplify adding extra dimensions in I/O variable creation

moment_kinetics/src/calculus.jl, moment_kinetics/src/gauss_legendre.jl, moment_kinetics/test/calculus_tests.jl, test_scripts/GaussLobattoLegendre_test.jl
Changes to correct the 1D matrix assembly functions. Documentation, simplification. Boundary conditions are now clearly only imposed when solving and ODE. Tests of this functionality could be added if desired. Demonstrated here so far is that differentiation does not require boundary conditions.
=> Correct 1 d matrix assembly

moment_kinetics/src/moment_kinetics.jl
Previously, we were printing to stdout, but this makes it more likely for the error message and stack trace to get lost, e.g. when `quietoutput()` is used in the tests.
=> When we catch an exception, print it to stderr before calling MPI.Abort

moment_kinetics/test/restart_interpolation_tests.jl
In the macOS CI job, temp directories have longer paths than on Linux, so our output file names must be a bit shorter.
=> Reduce max output file path lengths in restart_interpolation_tests.jl

.github/workflows/debug_checks.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/longtest.yml, .github/workflows/parallel_test.yml, .github/workflows/test.yml, .github/workflows/test_scripts.yml
=> Use latest version of julia-actions/cache

makie_post_processing/makie_post_processing/src/makie_post_processing.jl
Otherwise if those sections exist in `post_processing_input.toml`, they will cause an error when we check for unexpected sections (or for unexpected options).
=> Read distribution function sections in moments' input_dict for makie_post_processing()

.github/workflows/debug_checks.yml, .github/workflows/parallel_test.yml
Don't think it should cause a problem, but is unneeded now that we use OpenMPI from the Julia package manager for the CI jobs, and maybe there is some conflict that is causing intermittent failures in the parallel tests.
=> Remove mpi4py setup in parallel CI jobs

.github/workflows/debug_checks.yml, .github/workflows/parallel_test.yml
The option previously used only works for OpenMPI v4 and earlier - the options changed in v5 because they changed the backend (? see https://github.com/open-mpi/ompi/issues/8955). `--oversubscribe` seems more generic, so hopefully keeps working.
=> Use `--oversubscribe` for parallel CI jobs

moment_kinetics/src/external_sources.jl
When distributed-memory MPI parallelism is used, `coord.grid` only has the positions of points in the local grid, not the global grid, so it doesn't necessarily contain the end points of the global grid. We have to use `coord.L` to get the locations of the walls instead.
=> Fix "wall_exp_decay" source for distributed MPI

.github/workflows/longtest.yml, .github/workflows/parallel_test.yml, .github/workflows/test.yml, moment_kinetics/src/command_line_options.jl, moment_kinetics/test/setup.jl
On CI server, don't use `/tmp/` for output files.
I think putting files in `/tmp/` on the Github Actions CI servers might be the cause of the occasional failures of the tests we've been seeing recently. Maybe the files in `/tmp` get cleaned out frequently, and occasionally that cleaning happens while we are still using the file? Instead, put the test output files in subdirectories of `runs/`, but only when running on the CI server - otherwise still use `/tmp/` as normal.
=> Attempt to fix intermittent CI failures

moment_kinetics/src/file_io.jl
Units for the output binary file appear to be incorrect for the pressure. Here I have corrected the units to what I understand the normalisations are.
The old normalisation for p was 
```math
p_{ref} = n_{ref} T_{ref}
```
the corrected normalisation is 
```math
p_{ref} = n_{ref} m_{ref} c_{ref}^2
```
with $`c_{ref} = \sqrt{2 T_{ref}/m_{ref}}`$.
@johnomotani We should also check that the normalisation reported for the heat flux is correctly documented, since the units there also reference $`T_{ref}`$ and not $`m_{ref}c_{ref}^2`$.
May close #136.
=> Correct units for pressures to reflect normalisation used in the code.

moment_kinetics/test/restart_interpolation_tests.jl
Reduce maximum file name length in the restart interpolation test, to prevent an HDF5 error.
Hopefully fixes #272.
=> Fix failures of 'long tests' CI job

docs/src/post_processing_notes.md, machines/shared/machine_setup_stage_two.jl, makie_post_processing/makie_post_processing/src/makie_post_processing.jl
* Fixes `makie_post_processing.generate_example_input_file()`
* More portable call for Python from `machines/machine_setup.sh` when setting up a venv to use with `plots_post_processing`
* Mention `makie_post_processing.generate_example_input_file()` in the docs
=> Fix a couple of small errors in the setup process

moment_kinetics/test/restart_interpolation_tests.jl
Avoids filename-too-long errors on Github Actions servers.
=> Reduce length of "run_name" in restart_interpolation_tests.jl

docs/src/chebyshev.md
Addition of documentation of fundamental Chebyshev grid operations.
Please review the notes and give comments! @LucasMontoya4 @johnomotani @mabarnes
=> Chebyshev documentation

docs/src/manual_setup.md
To try address the problems encountered in #275, here I have tried to update the online documentation for the manual install, to reflect the current state of the machine setup scripts.
=> Suggestions for online documentation of manual setup

moment_kinetics/src/moment_kinetics.jl, moment_kinetics/test/jacobian_matrix_tests.jl
Avoids need to install StatsBase directly in base environment.
=> In tests, get StatsBase dependency from moment_kinetics package

moment_kinetics/src/boundary_conditions.jl
* Fix apparently incorrect prefactor in 'constant' neutral bc. We (almost?) never use the 'constant' boundary condition, so this bug should not have had any impact.
* Reduce allocations in enforce_neutral_wall_bc!() by passing in a buffer array.
=> Minor fix/optimisations for neutral wall bc

.github/workflows/parallel_test.yml, docs/src/developing.md, machines/archer/jobscript-precompile-no-run.template, machines/archer/jobscript-precompile.template, machines/archer/jobscript-restart.template, machines/archer/jobscript-run.template, machines/generic-batch-template/jobscript-precompile-no-run.template, machines/generic-batch-template/jobscript-precompile.template, machines/generic-batch-template/jobscript-restart.template, machines/generic-batch-template/jobscript-run.template, machines/machine_setup.sh, machines/marconi/jobscript-precompile-no-run.template, machines/marconi/jobscript-precompile.template, machines/marconi/jobscript-restart.template, machines/marconi/jobscript-run.template, machines/shared/submit-restart.sh, machines/shared/submit-run.sh, makie_post_processing/makie_post_processing/src/chodura_condition.jl, makie_post_processing/makie_post_processing/src/plots_for_variable.jl, moment_kinetics/src/fokker_planck_calculus.jl, moment_kinetics/src/looping.jl, precompile-kinetic-electrons.jl, precompile-makie-post-processing.jl, precompile-no-run.jl, precompile-plots-post-processing.jl, precompile.jl, precompile_dependencies.jl
Add an `@inbounds` to the definition of `@loop_*` macros. This ensures that we skip bounds checking in most of the performance-critical parts of the code, without having to use `--check-bounds=no` (which is slightly broken in Julia-1.10 and more broken in Julia-1.11).
If there are performance-critical places that do not use `@loop_*` macros, then explicit `@inbounds` is required. One such place is `fokker_planck_calculus`, which has had `@inbounds` added in this PR.
Note bounds checking can be switched on for testing/debugging with `--check-bounds=yes`.
Replaces #315.
=> @inbounds in loop macros

.github/workflows/debug_checks.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/longtest.yml, .github/workflows/parallel_test.yml, .github/workflows/test.yml, .github/workflows/test_scripts.yml, docs/Project.toml, docs/make-pdf.jl, docs/make.jl, docs/src/zz_plot_MMS_sequence.md, docs/src/zz_plot_sequence.md, docs/src/zz_plots_post_processing.md, moment_kinetics/Project.toml, moment_kinetics/src/moment_kinetics.jl, moment_kinetics/test/calculus_tests.jl, moment_kinetics/test/setup.jl
I got these updates ready, but I'm finding there are a few glitches with Julia-1.11.0 (it seems to crash when I try to use the `pkg>` interface from the REPL). There seems to be a fix for that problem which will be released in 1.11.1, so probably best to hold off on merging this at least until 1.11.1 is released.
=> Update CI jobs and documentation build to Julia-1.11

.github/workflows/test_scripts.yml, docs/make-pdf.jl, docs/make.jl, docs/src/zz_MKJacobianUtils.md, moment_kinetics/src/moment_kinetics.jl, test_scripts/check-MKJacobianUtils.jl, util/MKJacobianUtils.jl
It might be useful to inspect the Jacobian matrix that is used as a preconditioner for the kinetic electron solve. This PR adds a function to do this, which takes as input an existing kinetic electron simulation, assuming that it is most interesting to look at a 'typical' matrix from a somewhat settled-down simulation rather than one just produced by arbitrary initial conditions. To use:
```julia
julia> include("util/MKJacobianUtils.jl")
julia> J = get_electron_Jacobian_matrix(run_dir)
```
where `run_dir` is the path to the simulation to restart from. For more details [see the docs](https://mabarnes.github.io/moment_kinetics/previews/PR319/zz_MKJacobianUtils/#Main.MKJacobianUtils.get_electron_Jacobian_matrix-Tuple{Any}).
=> Script to get the Jacobian matrix for a kinetic electron solve

.github/workflows/debug_checks.yml
HDF5 fails to precompile when using OpenMPI_jll unless NCDatasets is also installed. NCDatasets was originally removed from the 'debug checks' CI test only because it didn't work for some reason, so makes sense to add it back now that it works again on the CI server, and for some strange reason helps HDF5 to precompile (https://github.com/JuliaIO/HDF5.jl/issues/1191).
=> Install NCDatasets in 'debug checks' CI test

.github/workflows/debug_checks.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/longtest.yml, .github/workflows/test_scripts.yml
Even after clearing the cache manually, the documentation workflow still fails unless we remove the julia-actions/cache action entirely. Don't understand why - error seems to be something to do with Conda.
=> Disable cache in documentation workflow

.github/workflows/debug_checks.yml, .github/workflows/parallel_test.yml
The linking bug that broke the latest version of HDF5_jll is now fixed (it was actually an error with OpenMPI_jll).
=> Unpin HDF5_jll version in CI tests with MPI

moment_kinetics/src/electron_kinetic_equation.jl, moment_kinetics/src/file_io.jl, moment_kinetics/src/initial_conditions.jl, moment_kinetics/src/moment_kinetics_input.jl, moment_kinetics/src/time_advance.jl, moment_kinetics/test/jacobian_matrix_tests.jl
Currently can only be used with `kinetic_electron_solver=explicit_time_evolving` because we need to pass the `scratch_pdf` struct containing also the ion/neutral variables in in order to write the output file.
=> Add debug IO outputs in `electron_kinetic_equation_euler_update!()`

.github/workflows/parallel_test.yml
Using 2 procs for the long tests instead of 4 seems to be about 10-20 minutes faster, even though Github claims their CI servers have 4 cores now (maybe it's actually 4 hyperthreads and 2 physical cores?).
=> Go back to using 2 procs for the 'long' tests in CI checks

docs/src/developing.md, moment_kinetics/debug_test/README.md, moment_kinetics/debug_test/runtest_template.jl, moment_kinetics/src/communication.jl, moment_kinetics/src/electron_kinetic_equation.jl, moment_kinetics/src/fokker_planck.jl, moment_kinetics/src/fokker_planck_calculus.jl, moment_kinetics/src/looping.jl, moment_kinetics/src/nonlinear_solvers.jl, moment_kinetics/test/fokker_planck_tests.jl, moment_kinetics/test/loop_setup_tests.jl, test_scripts/2D_FEM_assembly_test.jl, test_scripts/ImplicitCollisionsTest.jl, test_scripts/fkpl_direct_integration_test.jl
Anticipate that when calculating multi-species collisions, the collision operators for every species should be calculated together, to be able to re-use parts of the computation. Therefore rather than 'anyv' regions inside an outer loop over species, r, and z, we want to have an outer loop over r and z, containing inner loops over both species and velocity space - call this an 'anysv' region (for any 's'pecies or 'v'elocity).
Resolves #356.
=> Convert 'anyv' parallelisation to 'anysv'

moment_kinetics/Project.toml
This came from #327 originally, which turned out not to be needed.
=> Revert removal of NCDatasets from CI, accidentally merged in #383

.github/workflows/examples.yml, .github/workflows/parallel_test.yml, .github/workflows/test.yml, moment_kinetics/src/external_sources.jl, moment_kinetics/src/file_io.jl, moment_kinetics/src/load_data.jl, moment_kinetics/src/moment_kinetics_structs.jl, moment_kinetics/src/velocity_moments.jl
* Write the `source_T` arrays to output, since #380 allowed the external source temperature to be a spatially varying quantity.
* `'sinusoid'` option for external source profiles. Useful for periodic dimensions.
=> Save source temperature; 'sinusoid' source profile option

moment_kinetics/src/electron_kinetic_equation.jl, moment_kinetics/test/kinetic_electron_tests.jl, test_scripts/electron_debug_io_test.jl
Tests for 'time evolving' and explicit-timestepping versions of kinetic electron solver.
Also fixes bug with explicit solver where limiting electron timestep to a multiple of the ion timestep caused the simulation to fail to advance if the electron solve failed to converge, resulting in the ion timestep being reduced, which then made the electron solve even less likely to converge. This limitation seems not to have been necessary anyway, so it is just removed.
=> Tests for more kinetic electron solvers

.github/workflows/parallel_test.yml
* Split runs for different numbers of processes into different jobs.
* Only run 3 and 4 proc runs on merge to master.
* Don't build the `.so` system image. Seems to slow things down rather than speed them up (at the moment?).
=> Work around slow parallel test CI job

.github/workflows/longtest.yml
fail-fast had not been set previously for the parallel jobs.
=> Fix typo in longtest.yml CI job, and set fail-fast to false

moment_kinetics/src/runge_kutta.jl, moment_kinetics/test/fokker_planck_time_evolution_tests.jl, util/calculate_rk_coeffs.jl, util/test-rk-timestep.jl
Maybe useful for testing, etc. Backward Euler should be 'dissipative' in some sense, so this method might be useful for reaching close to steady state quickly?
Closes #347 - if all the terms included (e.g. the Fokker-Planck collision operator in a 0D simulation) are included in the implicit part of the timestep, then this is the backward Euler method.
=> 1st order IMEX method - forward/backward Euler
